// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5BXYn50hhnl9A0uVhYpFiZcXVJT-Wio',
    appId: '1:8482111292:android:98d16b74987c6784eda839',
    messagingSenderId: '8482111292',
    projectId: 'connect-riverpod',
    storageBucket: 'connect-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-pv8ZAKjvlk-MuCnlwcgOEHu5yc_Ct0',
    appId: '1:8482111292:ios:b59caa6fcf6eaef0eda839',
    messagingSenderId: '8482111292',
    projectId: 'connect-riverpod',
    storageBucket: 'connect-riverpod.appspot.com',
    androidClientId: '8482111292-qk3c9s07m5mab6a0tvafq0h0vkhichfs.apps.googleusercontent.com',
    iosClientId: '8482111292-6jfffsfigbv77ecukpq2lvlsj4fan8k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectRiverpod',
  );
}
